select 'ALTER SYSTEM KILL SESSION '''||sid||','||serial#||''' IMMEDIATE;' vsql from v$session where osuser = 'davidwalker';

ALTER SYSTEM KILL SESSION '136,23619' IMMEDIATE;
ALTER SYSTEM KILL SESSION '168,35239' IMMEDIATE;
ALTER SYSTEM KILL SESSION '455,11168' IMMEDIATE;