--http://stackoverflow.com/questions/7359702/how-do-i-obtain-a-query-execution-plan

SET SHOWPLAN_TEXT ON
SET SHOWPLAN_ALL ON
SET SHOWPLAN_XML ON
SET STATISTICS PROFILE ON
SET STATISTICS XML ON -- The is the recommended option to use

--SHOWPLAN_TEXT - Displays a basic text based estimated execution plan, without executing the query
--SHOWPLAN_ALL - Displays a text based estimated execution plan with cost estimations, without executing the query
--SHOWPLAN_XML - Displays an XML based estimated execution plan with cost estimations, without executing the query. This is equivalent to the "Display Estimated Execution Plan..." option in SQL Server Management Studio.
--STATISTICS PROFILE - Executes the query and displays a text based actual execution plan.
--STATISTICS XML - Executes the query and displays an XML based actual execution plan. This is equivalent to the "Include Actual Execution Plan" option in SQL Server Management Studio.

  |--Compute Scalar(DEFINE:([Expr1053]=CONVERT_IMPLICIT(int,[globalagg1060],0), [Expr1054]=CASE WHEN [globalagg1062]=(0) THEN NULL ELSE [globalagg1064] END, [Expr1055]=CASE WHEN [globalagg1066]=(0) THEN NULL ELSE [globalagg1068] END))
       |--Stream Aggregate(GROUP BY:([Union1041]) DEFINE:([globalagg1060]=SUM([partialagg1059]), [globalagg1062]=SUM([partialagg1061]), [globalagg1064]=SUM([partialagg1063]), [globalagg1066]=SUM([partialagg1065]), [globalagg1068]=SUM([partialagg1067])))
            |--Parallelism(Gather Streams, ORDER BY:([Union1041] DESC))
                 |--Stream Aggregate(GROUP BY:([Union1041]) DEFINE:([partialagg1059]=Count(*), [partialagg1061]=COUNT_BIG([Union1047]), [partialagg1063]=SUM([Union1047]), [partialagg1065]=COUNT_BIG([Union1045]), [partialagg1067]=SUM([Union1045])))
                      |--Sort(ORDER BY:([Union1041] DESC))
                           |--Concatenation
                                |--Compute Scalar(DEFINE:([Expr1012]=CONVERT_IMPLICIT(real(24),CASE WHEN [Olive3_Live].[dbo].[olive_line_lineitem].[deleted] as [li].[deleted]=N'false' AND [Olive3_Live].[dbo].[olive_plan_commitline].[deleted] as [cl].[deleted]=N'false' THEN CASE WHEN [Olive3_Live].[dbo].[olive_settings_costmodel].[name] as [cm].[name]=N'Fixed CPM' AND [Olive3_Live].[dbo].[olive_settings_costmodel].[deleted] as [cm].[deleted]=N'false' AND [Olive3_Live].[dbo].[performance_lineitem_performance].[date_of_activity] as [perf].[date_of_activity]>=[Olive3_Live].[dbo].[olive_plan_commitline].[start_date] as [cl].[start_date] AND [Olive3_Live].[dbo].[performance_lineitem_performance].[date_of_activity] as [perf].[date_of_activity]<=[Olive3_Live].[dbo].[olive_plan_commitline].[end_date] as [cl].[end_date] THEN (CONVERT_IMPLICIT(numeric(19,0),[Olive3_Live].[dbo].[performance_lineitem_performance].[impressions] as [perf].[impressions],0)*[Olive3_Live].[dbo].[olive_plan_medialine].[unit_cost] as [ml].[unit_cost])/(1000.) ELSE CASE WHEN [Olive3_Live].[dbo].[olive_settings_costmodel].[name] as [cm].[name]=N'Fixed CPC' AND [Olive3_Live].[dbo].[olive_settings_costmodel].[deleted] as [cm].[deleted]=N'false' AND [Olive3_Live].[dbo].[performance_lineitem_performance].[date_of_activity] as [perf].[date_of_activity]>=[Olive3_Live].[dbo].[olive_plan_commitline].[start_date] as [cl].[start_date] AND [Olive3_Live].[dbo].[performance_lineitem_performance].[date_of_activity] as [perf].[date_of_activity]<=[Olive3_Live].[dbo].[olive_plan_commitline].[end_date] as [cl].[end_date] THEN CONVERT_IMPLICIT(numeric(19,0),[Olive3_Live].[dbo].[performance_lineitem_performance].[clicks] as [perf].[clicks],0)*[Olive3_Live].[dbo].[olive_plan_medialine].[unit_cost] as [ml].[unit_cost] ELSE CASE WHEN [Olive3_Live].[dbo].[olive_settings_costmodel].[name] as [cm].[name]=N'Fixed CPA' AND [Olive3_Live].[dbo].[olive_settings_costmodel].[deleted] as [cm].[deleted]=N'false' THEN NULL ELSE CASE WHEN [Olive3_Live].[dbo].[olive_settings_purchasetype].[name] as [pt].[name]=N'FIXED' AND [Olive3_Live].[dbo].[olive_settings_costmodel].[name] as [cm].[name]=N'Added Value' AND [Olive3_Live].[dbo].[olive_settings_costmodel].[deleted] as [cm].[deleted]=N'false' THEN NULL ELSE CASE WHEN [Olive3_Live].[dbo].[olive_settings_costmodel].[name] as [cm].[name]=N'Fixed Cost' AND [Olive3_Live].[dbo].[olive_settings_costmodel].[deleted] as [cm].[deleted]=N'false' THEN NULL ELSE CASE WHEN [Olive3_Live].[dbo].[olive_settings_purchasetype].[name] as [pt].[name]<>N'FIXED' THEN CONVERT_IMPLICIT(numeric(38,8),[Olive3_Live].[dbo].[performance_lineitem_performance].[spend] as [perf].[spend],0) ELSE NULL END END END END END END ELSE NULL END,0)))
                                |    |--Nested Loops(Inner Join, OUTER REFERENCES:([perf].[deleted], [li].[deleted], [ml].[commitline_ptr_id]))
                                |         |--Nested Loops(Inner Join, OUTER REFERENCES:([cm].[purchase_type_id]))
                                |         |    |--Nested Loops(Inner Join, OUTER REFERENCES:([ml].[cost_model_id]))
                                |         |    |    |--Nested Loops(Inner Join, OUTER REFERENCES:([li].[media_line_id]))
                                |         |    |    |    |--Nested Loops(Inner Join, OUTER REFERENCES:([perf].[line_item_id]))
                                |         |    |    |    |    |--Parallelism(Distribute Streams, RoundRobin Partitioning)
                                |         |    |    |    |    |    |--Clustered Index Seek(OBJECT:([Olive3_Live].[dbo].[performance_lineitem_performance].[performance_pk] AS [perf]), SEEK:([perf].[date_of_activity] >= '2016-07-01' AND [perf].[date_of_activity] <= '2016-07-15') ORDERED FORWARD)
                                |         |    |    |    |    |--Clustered Index Seek(OBJECT:([Olive3_Live].[dbo].[olive_line_lineitem].[PK__olive_li__3213E83F5733CBC5] AS [li]), SEEK:([li].[id]=[Olive3_Live].[dbo].[performance_lineitem_performance].[line_item_id] as [perf].[line_item_id]) ORDERED FORWARD)
                                |         |    |    |    |--Clustered Index Seek(OBJECT:([Olive3_Live].[dbo].[olive_plan_medialine].[PK__olive_pl__BCE20BFF1EBA6878] AS [ml]), SEEK:([ml].[commitline_ptr_id]=[Olive3_Live].[dbo].[olive_line_lineitem].[media_line_id] as [li].[media_line_id]) ORDERED FORWARD)
                                |         |    |    |--Clustered Index Seek(OBJECT:([Olive3_Live].[dbo].[olive_settings_costmodel].[PK__olive_se__3213E83F7894BF90] AS [cm]), SEEK:([cm].[id]=[Olive3_Live].[dbo].[olive_plan_medialine].[cost_model_id] as [ml].[cost_model_id]) ORDERED FORWARD)
                                |         |    |--Clustered Index Seek(OBJECT:([Olive3_Live].[dbo].[olive_settings_purchasetype].[PK__olive_se__3213E83F5B301089] AS [pt]), SEEK:([pt].[id]=[Olive3_Live].[dbo].[olive_settings_costmodel].[purchase_type_id] as [cm].[purchase_type_id]) ORDERED FORWARD)
                                |         |--Clustered Index Seek(OBJECT:([Olive3_Live].[dbo].[olive_plan_commitline].[PK__olive_pl__1789B3DB237F1D95] AS [cl]), SEEK:([cl].[plan_line_id]=[Olive3_Live].[dbo].[olive_plan_medialine].[commitline_ptr_id] as [ml].[commitline_ptr_id]),  WHERE:(CASE WHEN [Olive3_Live].[dbo].[performance_lineitem_performance].[deleted] as [perf].[deleted]=N'true' OR [Olive3_Live].[dbo].[olive_line_lineitem].[deleted] as [li].[deleted]=N'true' OR [Olive3_Live].[dbo].[olive_plan_commitline].[deleted] as [cl].[deleted]=N'true' THEN 'true' ELSE 'false' END='false') ORDERED FORWARD)
                                |--Compute Scalar(DEFINE:([Expr1033]=NULL, [Expr1035]=CASE WHEN [Olive3_Live].[dbo].[olive_line_lineitem].[deleted]=N'false' AND [Olive3_Live].[dbo].[olive_plan_commitline].[deleted] as [cl].[deleted]=N'false' THEN [Olive3_Live].[dbo].[olive_plan_commitline].[total_net] as [cl].[total_net]/CONVERT_IMPLICIT(real(24),[Expr1021]*(datediff(day,CONVERT_IMPLICIT(datetimeoffset(7),[Olive3_Live].[dbo].[olive_plan_commitline].[start_date] as [cl].[start_date],0),CONVERT_IMPLICIT(datetimeoffset(7),[Olive3_Live].[dbo].[olive_plan_commitline].[end_date] as [cl].[end_date],0))+(1)),0) ELSE NULL END))
                                     |--Nested Loops(Inner Join, WHERE:([Olive3_Live].[dbo].[dates].[DATE_OF_ACTIVITY]>=[Olive3_Live].[dbo].[olive_plan_commitline].[start_date] as [cl].[start_date] AND [Olive3_Live].[dbo].[dates].[DATE_OF_ACTIVITY]<=[Olive3_Live].[dbo].[olive_plan_commitline].[end_date] as [cl].[end_date]))
                                          |--Hash Match(Inner Join, HASH:([cl].[plan_line_id])=([Olive3_Live].[dbo].[olive_line_lineitem].[media_line_id]), RESIDUAL:([Olive3_Live].[dbo].[olive_line_lineitem].[media_line_id]=[Olive3_Live].[dbo].[olive_plan_commitline].[plan_line_id] as [cl].[plan_line_id] AND CASE WHEN [Olive3_Live].[dbo].[olive_line_lineitem].[deleted]=N'true' OR [Olive3_Live].[dbo].[olive_plan_commitline].[deleted] as [cl].[deleted]=N'true' THEN 'true' ELSE 'false' END='false'))
                                          |    |--Bitmap(HASH:([cl].[plan_line_id]), DEFINE:([Bitmap1075]))
                                          |    |    |--Hash Match(Inner Join, HASH:([ml].[commitline_ptr_id])=([cl].[plan_line_id]))
                                          |    |         |--Bitmap(HASH:([ml].[commitline_ptr_id]), DEFINE:([Bitmap1072]))
                                          |    |         |    |--Parallelism(Repartition Streams, Hash Partitioning, PARTITION COLUMNS:([ml].[commitline_ptr_id]))
                                          |    |         |         |--Hash Match(Inner Join, HASH:([cm].[id])=([ml].[cost_model_id]), RESIDUAL:([Olive3_Live].[dbo].[olive_plan_medialine].[cost_model_id] as [ml].[cost_model_id]=[Olive3_Live].[dbo].[olive_settings_costmodel].[id] as [cm].[id]))
                                          |    |         |              |--Bitmap(HASH:([cm].[id]), DEFINE:([Bitmap1071]))
                                          |    |         |              |    |--Parallelism(Distribute Streams, Broadcast Partitioning)
                                          |    |         |              |         |--Clustered Index Scan(OBJECT:([Olive3_Live].[dbo].[olive_settings_costmodel].[PK__olive_se__3213E83F7894BF90] AS [cm]), WHERE:([Olive3_Live].[dbo].[olive_settings_costmodel].[name] as [cm].[name]=N'Fixed Cost'))
                                          |    |         |              |--Clustered Index Scan(OBJECT:([Olive3_Live].[dbo].[olive_plan_medialine].[PK__olive_pl__BCE20BFF1EBA6878] AS [ml]), WHERE:(PROBE([Bitmap1071],[Olive3_Live].[dbo].[olive_plan_medialine].[cost_model_id] as [ml].[cost_model_id],N'[IN ROW]')))
                                          |    |         |--Parallelism(Repartition Streams, Hash Partitioning, PARTITION COLUMNS:([cl].[plan_line_id]))
                                          |    |              |--Clustered Index Scan(OBJECT:([Olive3_Live].[dbo].[olive_plan_commitline].[PK__olive_pl__1789B3DB237F1D95] AS [cl]), WHERE:(PROBE([Bitmap1072],[Olive3_Live].[dbo].[olive_plan_commitline].[plan_line_id] as [cl].[plan_line_id],N'[IN ROW]')))
                                          |    |--Parallelism(Repartition Streams, Hash Partitioning, PARTITION COLUMNS:([Olive3_Live].[dbo].[olive_line_lineitem].[media_line_id]), WHERE:(PROBE([Bitmap1075],[Olive3_Live].[dbo].[olive_line_lineitem].[media_line_id])))
                                          |         |--Nested Loops(Inner Join)
                                          |              |--Table Spool
                                          |              |    |--Segment
                                          |              |         |--Sort(ORDER BY:([Olive3_Live].[dbo].[olive_line_lineitem].[media_line_id] ASC, [Olive3_Live].[dbo].[olive_line_lineitem].[deleted] ASC))
                                          |              |              |--Parallelism(Repartition Streams, Hash Partitioning, PARTITION COLUMNS:([Olive3_Live].[dbo].[olive_line_lineitem].[media_line_id], [Olive3_Live].[dbo].[olive_line_lineitem].[deleted]))
                                          |              |                   |--Clustered Index Scan(OBJECT:([Olive3_Live].[dbo].[olive_line_lineitem].[PK__olive_li__3213E83F5733CBC5]))
                                          |              |--Nested Loops(Inner Join, WHERE:((1)))
                                          |                   |--Compute Scalar(DEFINE:([Expr1021]=CONVERT_IMPLICIT(int,[Expr1074],0)))
                                          |                   |    |--Stream Aggregate(DEFINE:([Expr1074]=Count(*)))
                                          |                   |         |--Table Spool
                                          |                   |--Table Spool
                                          |--Table Spool
                                               |--Clustered Index Seek(OBJECT:([Olive3_Live].[dbo].[dates].[PK__dates__5CF58F2A77568294]), SEEK:([Olive3_Live].[dbo].[dates].[DATE_OF_ACTIVITY] >= '2016-07-01' AND [Olive3_Live].[dbo].[dates].[DATE_OF_ACTIVITY] <= '2016-07-15') ORDERED FORWARD)