SELECT   I.ORGANIZATION_ID
,        HOU.NAME
,        I.ORG_INFORMATION_CONTEXT
,        HL.MEANING   
FROM     HR_ORGANIZATION_UNITS HOU
,        HR_ORGANIZATION_INFORMATION I
,        HR_LOOKUPS HL
WHERE    1=1
AND      HOU.ORGANIZATION_ID = I.ORGANIZATION_ID
AND      I.ORGANIZATION_ID IN (1106,1126)
AND      I.ORG_INFORMATION_CONTEXT = 'CLASS'
AND      I.ORG_INFORMATION1 = HL.LOOKUP_CODE (+)
AND      HL.LOOKUP_TYPE (+) = 'ORG_CLASS'