-- MTL_ORG_ASSIGN_V

SELECT DISTINCT M.ORGANIZATION_ID , M.ORGANIZATION_CODE , H.NAME , MSI.INVENTORY_ITEM_ID , UOMT.UNIT_OF_MEASURE , UOMT.UNIT_OF_MEASURE_TL , M.SALES_ACCOUNT , M.COST_OF_SALES_ACCOUNT , M.EXPENSE_ACCOUNT , M.ENCUMBRANCE_ACCOUNT , 'Y' , M.MASTER_ORGANIZATION_ID , M.EAM_ENABLED_FLAG ,MSI.SECONDARY_UOM_CODE ,MSI.TRACKING_QUANTITY_IND ,MSI.SECONDARY_DEFAULT_IND ,MSI.ONT_PRICING_QTY_SOURCE ,MSI.DUAL_UOM_DEVIATION_HIGH ,MSI.DUAL_UOM_DEVIATION_LOW
FROM MTL_PARAMETERS M
, HR_ORGANIZATION_UNITS H 
, MTL_SYSTEM_ITEMS_B MSI 
, MTL_UNITS_OF_MEASURE_TL UOMT
WHERE H.ORGANIZATION_ID = M.ORGANIZATION_ID
AND NVL(H.DATE_TO, SYSDATE+1) > SYSDATE
AND MSI.ORGANIZATION_ID = M.ORGANIZATION_ID
AND UOMT.UOM_CODE = MSI.PRIMARY_UOM_CODE
AND UOMT.LANGUAGE = USERENV('LANG')
UNION ALL
SELECT DISTINCT M.ORGANIZATION_ID , M.ORGANIZATION_CODE , H.NAME , INVIDIT3.GET_INV_ITEM_ID , NULL , NULL , M.SALES_ACCOUNT , M.COST_OF_SALES_ACCOUNT , M.EXPENSE_ACCOUNT , M.ENCUMBRANCE_ACCOUNT , 'N' , M.MASTER_ORGANIZATION_ID , M.EAM_ENABLED_FLAG ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL
FROM MTL_PARAMETERS M 
, HR_ORGANIZATION_UNITS H 
WHERE H.ORGANIZATION_ID = M.ORGANIZATION_ID 
AND NVL(H.DATE_TO, SYSDATE+1) > SYSDATE
AND NOT EXISTS
   (
   SELECT   ORGANIZATION_ID
   FROM     MTL_SYSTEM_ITEMS_B
   WHERE    INVENTORY_ITEM_ID = INVIDIT3.GET_INV_ITEM_ID
   AND      ORGANIZATION_ID = M.ORGANIZATION_ID
   )